baseURL = "https://jgabriel.eu"
title = "Jorge Gabriel Azevedo"
copyright = "Copyright © 2020, Jorge Gabriel Azevedo; all rights reserved."
paginate = "6"
languageCode = "pt-pt"
DefaultContentLanguage = "pt-pt"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-167181822-1"
DisqusShortname = ""
theme = "hugo-theme-chunky-poster"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "mylife"
    name = "My Life"
    url = "/mylife/"
    weight = 0
  [[menu.main]]
    identifier = "myprojects"
    name = "My Projects"
    url = "/project/"
    weight = 0
  [[menu.main]]
    identifier = "notebook"
    name = "Notebook"
    url = "/article/"
    weight = 0
#  [[menu.main]]
#    identifier = "mytoolset"
#    name = "My Tool Set"
#    url = "/mytoolset/"
#    weight = 0

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
author = "authors"

[params]
  author = "Jorge Gabriel Azevedo"
  description = "Engenheiro de Sistemas <br> Consultor na Deloitte Portugal <br> Web developer"
  homepageImage = "/images/homepage-image.jpg"
  share = true
  showLanguageSwitcher = false

  # Custom CSS and JS. Relative to /static/css and /static/js respectively.
  customCSS = ["external-css.css", "timeline.css"]
  customJS = ["external-js.js"]

  customExternalCSS = ["https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css"]
  customExternalJS = ["https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js"]

  [params.social]
    rss = false
    #email = "example@example.com"
    #facebook = "https://facebook.com"
    twitter = "https://twitter.com/wultyc"
    linkedin = "https://linkedin.com/in/j-gabriel/"
    #stack-overflow = "https://stackoverflow.com"
    instagram = "https://instagram.com/wultyc"
    github = "https://github.com/wultyc"
    #weibo = "https://www.weibo.com"
    #medium = "https://medium.com"
    #pinterest = "https://pinterest.com"
    #reddit = "https://reddit.com"
    #gitlab = "https://gitlab.com"
    #mastodon = "https://mastodon.social"
    #keybase = "https://keybase.io/"

  [params.prismJS]
    enable = true
    theme = ""

  [params.commento]
    enable = false
    url = "https://commento.io"

[markup]
  [markup.highlight]
    codeFences = false

[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true

[markup.goldmark.renderer]
  unsafe= true