baseURL = "https://wultyc.tk"
title = "jGabriel"
copyright = "Copyright © 2020, Jorge Gabriel Azevedo; all rights reserved."
paginate = 2
languageCode = "pt"
DefaultContentLanguage = "pt"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = ""
DisqusShortname = ""
theme = "hugo-theme-chunky-poster"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "mylife"
    name = "My Life"
    url = "/mylife/"
    weight = 0
  [[menu.main]]
    identifier = "myprojects"
    name = "My Projects"
    url = "/myprojects/"
    weight = 0

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
author = "authors"

[params]
  author = "Hugo Authors"
  description = "Lorem ipsum dolor sit amet."
  homepageImage = "/images/homepage-image.jpg"
  share = true
  showLanguageSwitcher = false

  # Custom CSS and JS. Relative to /static/css and /static/js respectively.
  customCSS = []
  customJS = []

  [params.social]
    rss = false
    #email = "example@example.com"
    #facebook = "https://facebook.com"
    twitter = "https://twitter.com/wultyc"
    linkedin = "https://linkedin.com/in/j-gabriel/"
    #stack-overflow = "https://stackoverflow.com"
    instagram = "https://instagram.com/wultyc"
    github = "https://github.com/wultyc"
    #weibo = "https://www.weibo.com"
    #medium = "https://medium.com"
    #pinterest = "https://pinterest.com"
    #reddit = "https://reddit.com"
    #gitlab = "https://gitlab.com"
    #mastodon = "https://mastodon.social"
    #keybase = "https://keybase.io/"

  [params.prismJS]
    enable = true
    theme = ""

  [params.commento]
    enable = true
    url = "https://commento.io"

[markup]
  [markup.highlight]
    codeFences = false

[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
