baseURL = 'https://example.org/'
languageCode = 'en-us'

[params]
  # Website pages metadata
  siteAuthor = ""
  title = ''
  description = ""
  keywords = ""

  favicon = "favicon.ico"

  # Website Resources
  css = [
    "css/bootstrap.min.css",
    "css/mklb.css",
    "css/materialdesignicons.min.css",
    "css/tiny-slider.css",
    "css/style.css",
    "css/colors/default.css"
  ]

  js = [
    "js/jquery.min.js", 
    "js/bootstrap.bundle.min.js", 
    "js/gumshoe.js", 
    "js/tiny-slider.js ", 
    "js/tiny-slider-init.js ", 
    "js/mklb.js", 
    "js/contact.js", 
    "js/counter.init.js", 
    "js/feather.min.js", 
    "js/jquery.ripples-min.js", 
    "js/ripple.init.js", 
    "js/typed.js", 
    "js/typed.init.js", 
    "js/switcher.js", 
    "js/app.js"
  ]

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
